#
app:
  extends:
    file: common.yml
    service: app

  # Not too sure about this as there seem to be IO errors with using volumes like
  # this, eg corrupt files and missing files.
  # We use the sakai.properties from the production build
  volumes:
   - ./tomcat/lib:/opt/tomcat/sakai-lib
   - ./tomcat/components:/opt/tomcat/components
   - ./tomcat/webapps:/opt/tomcat/webapps
   - ./override:/opt/tomcat/sakai/override
   - ./placeholder.properties:/opt/tomcat/sakai/placeholder.properties
   - ./sakai.quartz.properties:/opt/tomcat/sakai/sakai.quartz.properties
   - ./log4j.properties:/opt/tomcat/sakai/log4j.properties
   - ./local.properties:/opt/tomcat/sakai/local.properties
   - ./sakai-jaas.conf:/opt/tomcat/sakai/sakai-jaas.conf
   - ./krb5.conf:/opt/tomcat/sakai/krb5.conf
   - ./sakai-keytab:/opt/tomcat/sakai/sakai-keytab
   - ./jgroups-config.xml:/opt/tomcat/sakai/jgroups-config.xml
   # Yourkit stuff
   - ./libyjpagent.so:/opt/yjp/bin/linux-x86-64/libyjpagent.so
   - ./startup_with_yjp.sh:/opt/tomcat/bin/startup_with_yjp.sh
  command: /opt/tomcat/bin/catalina.sh jpda run
  #command: /opt/tomcat/bin/startup_with_yjp.sh
  # This is needed to allow jmap (heap dumps_) to work, otherwise it fails
  security_opt:
  - seccomp:unconfined
  environment:
   # In development this means we can read files without anything special
   SAKAI_USER: root
   SENTRY_DSN:
   CATALINA_OPTS_EXTRA:
  links:
   - db
   - solr
  ports:
   - "8080:8080"
   - "127.0.0.1:8000:8000"
   - "127.0.0.1:8009:8009"
   - "127.0.0.1:5400:5400"
   - "127.0.0.1:8025:8025"
   # Yourkit Profiling port
   - "127.0.0.1:10001:10001"

db:
  extends:
    file: common.yml
    service: db
  ports:
   - "3306:3306"

web:
  extends:
    file: common.yml
    service: web
  links:
   - app

solr:
  extends:
    file: common.yml
    service: solr
