# This builds an image for production
app:
  extends:
    file: common.yml
    service: app
  build: .
  environment:
   SENTRY_DSN:

  command: /opt/tomcat/bin/catalina.sh run
  links:
   - db

db:
  extends:
    file: common.yml
    service: db
